services:
  - type: web
    name: spotify-yt-downloader
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn web_app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
